### ISSUE TITLE
Custom Derma for Config Tool

### ISSUE THREAD

**Issue by landnevermore** [Guthen/guthscpkeycard#2]
maybe you could start using PixelUI or XeninUI so the Addons look more "Modern"
(would prefer PixelUI but thats up to you)

**Comment by Guthen** [comment]
(I will just repeat myself from Discord for an official response)

This issue would be better made in [Guthen/guthscpbase](https://github.com/Guthen/guthscpbase) since it will be easier for me to manage a common UI design for every of my SCPs addons. Also I don't want people to have to download more mandatory addons to make the UI working, so if I ever implement PixelUI or XeninUI, they will be completely optionals.
